package com.ar2lda.fac.model;

public enum PermissaoFuncional {
    DOCUMENTO_CONSULTAR,
    DOCUMENTO_CRIAR,
    DOCUMENTO_EDITAR_RASCUNHO,
    DOCUMENTO_ELIMINAR_RASCUNHO,
    DOCUMENTO_EMITIR,
    DOCUMENTO_ANULAR,
    DOCUMENTO_OBTER_PDF,
    SERIE_CONSULTAR,
    SERIE_GERIR,
    SERIE_CONFIGURAR_AT,
    AUDITORIA_CONSULTAR
}
