package com.ar2lda.fac.model;

public enum TipoAuditoriaEvento {
    DOCUMENTO_CRIADO,
    DOCUMENTO_ALTERADO,
    DOCUMENTO_ELIMINADO_RASCUNHO,
    DOCUMENTO_EMITIDO,
    DOCUMENTO_ANULADO,
    DOCUMENTO_PDF_GERADO,
    SERIE_CRIADA,
    SERIE_ALTERADA,
    SERIE_CODIGO_AT_ALTERADO,
    SERIE_ELIMINADA,
    LOGIN_SUCESSO,
    LOGIN_FALHADO,
    TENTATIVA_ANULACAO_NEGADA
}
