package com.ar2lda.fac.model;

public enum TipoAuditoriaEvento {
    DOCUMENTO_CRIADO,
    DOCUMENTO_ALTERADO,
    DOCUMENTO_ELIMINADO_RASCUNHO,
    DOCUMENTO_EMITIDO,
    DOCUMENTO_ANULADO,
    DOCUMENTO_PDF_GERADO,
    RECEBIMENTO_REGISTADO,
    SERIE_CRIADA,
    SERIE_ALTERADA,
    SERIE_CODIGO_AT_ALTERADO,
    SERIE_ELIMINADA,
    LOGIN_SUCESSO,
    LOGIN_FALHADO,
    TENTATIVA_ANULACAO_NEGADA,
    UTILIZADOR_CRIADO,
    UTILIZADOR_ALTERADO,
    UTILIZADOR_ESTADO_ALTERADO,
    UTILIZADOR_PERFIL_ALTERADO,
    UTILIZADOR_PASSWORD_REDEFINIDA,
    EMPRESA_ALTERADA,
    EMPRESA_LOGOTIPO_ALTERADO,
    EMPRESA_LOGOTIPO_REMOVIDO,
    TENTATIVA_ADMINISTRATIVA_NEGADA,
    TENTATIVA_ULTIMO_ADMINISTRADOR_NEGADA
}
