ALTER TABLE codpostal
    ADD COLUMN distrito varchar(100),
    ADD COLUMN concelho varchar(100),
    ADD COLUMN freguesia varchar(100);

CREATE TABLE codpostal_localidade (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codpostal_id varchar(20) NOT NULL,
    nome varchar(180) NOT NULL,
    CONSTRAINT codpostal_localidade_codpostal_fkey
        FOREIGN KEY (codpostal_id) REFERENCES codpostal(id),
    CONSTRAINT uk_codpostal_localidade_codigo_nome UNIQUE (codpostal_id, nome)
);

CREATE INDEX ix_codpostal_id_pattern ON codpostal (id text_pattern_ops);
CREATE INDEX ix_codpostal_nome_lower ON codpostal (lower(nome) text_pattern_ops);
CREATE INDEX ix_codpostal_localidade_nome_lower ON codpostal_localidade (lower(nome) text_pattern_ops);
