-- Fiscal foundation; emitted historical documents are deliberately not recalculated/backfilled.
ALTER TABLE riva ADD COLUMN mercado varchar(40) NOT NULL DEFAULT 'NACIONAL',
 ADD COLUMN tratamento_liquidacao varchar(30) NOT NULL DEFAULT 'NORMAL',
 ADD COLUMN fundamento_fiscal varchar(500), ADD COLUMN id_misencao varchar(3) REFERENCES misencao(id),
 ADD COLUMN jurisdicao varchar(10) NOT NULL DEFAULT 'PT', ADD COLUMN territorio_fiscal varchar(20) NOT NULL DEFAULT 'CONTINENTE';
ALTER TABLE misencao ADD COLUMN descricao_oficial varchar(500), ADD COLUMN fundamento_oficial varchar(500),
 ADD COLUMN fonte_oficial varchar(1000), ADD COLUMN versao_oficial varchar(40);
ALTER TABLE artigo ADD COLUMN id_misencao varchar(3) REFERENCES misencao(id), ADD COLUMN fundamento_fiscal varchar(500);
ALTER TABLE cliente ALTER COLUMN id_codpostal DROP NOT NULL;
ALTER TABLE documento_comercial ALTER COLUMN cliente_cod_postal DROP NOT NULL;
ALTER TABLE documento_comercial DROP CONSTRAINT ck_documento_fiscal_snapshot_version;
ALTER TABLE documento_comercial ADD CONSTRAINT ck_documento_fiscal_snapshot_version CHECK(fiscal_snapshot_version IS NULL OR fiscal_snapshot_version IN(1,2,3));
CREATE TABLE taxa_iva_territorial(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 jurisdicao varchar(10) NOT NULL,territorio varchar(20) NOT NULL,categoria varchar(20) NOT NULL,
 valor numeric(5,2) NOT NULL CHECK(valor>=0),vigente_desde date,vigente_ate date,
 CHECK(vigente_desde IS NULL OR vigente_ate IS NULL OR vigente_desde<=vigente_ate));
-- Current published reference rates, not reconstruction of past legislation. Future dated entries are supported.
-- CIVA art18; Oficio-Circulado 25045/2024, consulted 2026-10-07.
INSERT INTO taxa_iva_territorial(jurisdicao,territorio,categoria,valor) VALUES
 ('PT','CONTINENTE','ISENTA',0),('PT','CONTINENTE','REDUZIDA',6),('PT','CONTINENTE','INTERMEDIA',13),('PT','CONTINENTE','NORMAL',23),
 ('PT','ACORES','ISENTA',0),('PT','ACORES','REDUZIDA',4),('PT','ACORES','INTERMEDIA',9),('PT','ACORES','NORMAL',16),
 ('PT','MADEIRA','ISENTA',0),('PT','MADEIRA','REDUZIDA',4),('PT','MADEIRA','INTERMEDIA',12),('PT','MADEIRA','NORMAL',22);
ALTER TABLE documento_comercial ADD COLUMN fiscal_motor_version integer;
ALTER TABLE documento_comercial ADD COLUMN fiscal_recalculo_aviso boolean NOT NULL DEFAULT false;
ALTER TABLE documento_comercial ADD COLUMN fiscal_mercado varchar(40);
ALTER TABLE documento_comercial ADD COLUMN fiscal_tratamento_liquidacao varchar(30);
ALTER TABLE documento_comercial ADD COLUMN fiscal_fundamento varchar(500);
ALTER TABLE documento_comercial ADD COLUMN fiscal_misencao_codigo varchar(3);
ALTER TABLE documento_comercial ADD COLUMN fiscal_jurisdicao varchar(10);
ALTER TABLE documento_comercial ADD COLUMN fiscal_territorio_fiscal varchar(20);
ALTER TABLE linha_documento_comercial ADD COLUMN iva_calculado numeric(19,6);
ALTER TABLE linha_documento_comercial ADD COLUMN iva_liquidado numeric(19,6);
ALTER TABLE linha_documento_comercial ADD COLUMN fiscal_misencao_codigo varchar(3);
ALTER TABLE linha_documento_comercial ADD COLUMN fiscal_fundamento varchar(500);
ALTER TABLE linha_documento_comercial ADD COLUMN fiscal_tratamento_liquidacao varchar(30);
ALTER TABLE linha_documento_comercial ADD COLUMN fiscal_projecao_qr varchar(20);
