--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.3 (Debian 16.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: armazem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.armazem (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    morada character varying(60) NOT NULL,
    morada1 character varying(60),
    id_codpostal character varying(20) NOT NULL,
    localidade character varying(50) NOT NULL,
    id_pais character varying(3) NOT NULL,
    id_freguesia character varying(6)
);


--
-- Name: armazem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.armazem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.armazem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: artigo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artigo (
    codigo character varying(50) NOT NULL,
    abreviatura character varying(30),
    codigo_identificacao character varying(100),
    descricao character varying(80) NOT NULL,
    unidade character varying(3) NOT NULL,
    id_familia bigint NOT NULL,
    peso numeric(15,3),
    id_iva_compra character varying(20) NOT NULL,
    id_iva_venda character varying(20) NOT NULL,
    pvp numeric(19,6) NOT NULL,
    inativo boolean DEFAULT false NOT NULL,
    retencao boolean DEFAULT false NOT NULL,
    observacoes character varying(250),
    CONSTRAINT ck_artigo_codigo CHECK (((codigo)::text ~ '^[A-Z0-9]{1,50}$'::text)),
    CONSTRAINT ck_artigo_peso CHECK (((peso IS NULL) OR (peso >= (0)::numeric))),
    CONSTRAINT ck_artigo_pvp CHECK ((pvp >= (0)::numeric))
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente (
    id bigint NOT NULL,
    nome character varying(80) NOT NULL,
    morada character varying(60) NOT NULL,
    morada1 character varying(60),
    localidade character varying(50),
    id_codpostal character varying(20) NOT NULL,
    nif character varying(20) NOT NULL,
    id_moeda character varying(3) NOT NULL,
    tel character varying(20),
    tm character varying(20),
    email character varying(120),
    email1 character varying(120),
    id_mpagamento integer,
    id_ppagamento character varying(3),
    id_riva character varying(3) DEFAULT 'CON'::character varying NOT NULL,
    tspiva character varying(20),
    iban character varying(34),
    retencao boolean DEFAULT false NOT NULL,
    id_transporte integer NOT NULL,
    inativo boolean DEFAULT false NOT NULL,
    observacoes character varying(300),
    id_pais character varying(3) NOT NULL
);


--
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: codpostal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.codpostal (
    id character varying(20) NOT NULL,
    nome character varying(50) NOT NULL
);


--
-- Name: documento_comercial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documento_comercial (
    id bigint NOT NULL,
    id_tipo_documento character varying(3) NOT NULL,
    serie character varying(10) NOT NULL,
    numero_documento bigint,
    estado character varying(20) NOT NULL,
    data_emissao date NOT NULL,
    id_cliente bigint NOT NULL,
    id_morada_envio bigint,
    id_armazem_carga bigint NOT NULL,
    id_moeda character varying(3) NOT NULL,
    id_riva character varying(3) NOT NULL,
    id_mpagamento integer,
    id_ppagamento character varying(3) NOT NULL,
    id_transporte integer NOT NULL,
    cliente_nome character varying(100) NOT NULL,
    cliente_nif character varying(20) NOT NULL,
    cliente_morada character varying(60) NOT NULL,
    cliente_morada1 character varying(60),
    cliente_cod_postal character varying(20) NOT NULL,
    cliente_localidade character varying(50),
    cliente_pais character varying(3) NOT NULL,
    envio_nome character varying(80),
    envio_morada character varying(60),
    envio_morada1 character varying(60),
    envio_cod_postal character varying(20),
    envio_localidade character varying(50),
    envio_pais character varying(3),
    data_carga date NOT NULL,
    hora_carga time without time zone,
    matricula character varying(100),
    carga_nome character varying(100) NOT NULL,
    carga_morada character varying(60) NOT NULL,
    carga_morada1 character varying(60),
    carga_cod_postal character varying(20) NOT NULL,
    carga_localidade character varying(50) NOT NULL,
    carga_pais character varying(3) NOT NULL,
    data_descarga date,
    hora_descarga time without time zone,
    descarga_morada character varying(60),
    descarga_morada1 character varying(60),
    descarga_cod_postal character varying(20),
    descarga_localidade character varying(50),
    descarga_pais character varying(3),
    valor_bruto numeric(19,6) DEFAULT 0 NOT NULL,
    valor_desconto numeric(19,6) DEFAULT 0 NOT NULL,
    valor_isento numeric(19,6) DEFAULT 0 NOT NULL,
    valor_sujeito_reduzida numeric(19,6) DEFAULT 0 NOT NULL,
    valor_sujeito_intermedia numeric(19,6) DEFAULT 0 NOT NULL,
    valor_sujeito_normal numeric(19,6) DEFAULT 0 NOT NULL,
    valor_iva_reduzida numeric(19,6) DEFAULT 0 NOT NULL,
    valor_iva_intermedia numeric(19,6) DEFAULT 0 NOT NULL,
    valor_iva_normal numeric(19,6) DEFAULT 0 NOT NULL,
    valor_retencao numeric(19,6) DEFAULT 0 NOT NULL,
    peso numeric(15,3),
    observacoes character varying(250),
    momento_emissao timestamp with time zone,
    id_emissor character varying(20),
    anulado boolean DEFAULT false NOT NULL,
    impresso boolean DEFAULT false NOT NULL,
    data_vencimento date NOT NULL,
    liquidado boolean DEFAULT false NOT NULL,
    valor_iva_total numeric(19,6) DEFAULT 0 NOT NULL,
    valor_total numeric(19,6) DEFAULT 0 NOT NULL,
    codigo_validacao_at character varying(100),
    atcud character varying(150),
    qr_payload text,
    qr_payload_version character varying(20),
    numero_documento_completo character varying(80),
    CONSTRAINT ck_documento_comercial_estado CHECK (((estado)::text = ANY ((ARRAY['RASCUNHO'::character varying, 'EMITIDO'::character varying])::text[]))),
    CONSTRAINT ck_documento_comercial_peso CHECK (((peso IS NULL) OR (peso >= (0)::numeric)))
);


--
-- Name: documento_comercial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documento_comercial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documento_comercial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documento_financeiro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documento_financeiro (
    id bigint NOT NULL,
    id_cliente bigint NOT NULL,
    id_tipo_documento character varying(3) NOT NULL,
    serie character varying(10) NOT NULL,
    numero_documento bigint NOT NULL,
    data_emissao date NOT NULL,
    id_moeda character varying(3) NOT NULL,
    valor_pagamento_bruto numeric(19,6) DEFAULT 0 NOT NULL,
    valor_desconto_financeiro numeric(19,6) DEFAULT 0 NOT NULL,
    valor_pagamento_liquido numeric(19,6) DEFAULT 0 NOT NULL,
    id_mpagamento integer NOT NULL,
    data_hora_operacao timestamp with time zone NOT NULL,
    id_emissor character varying(20) NOT NULL,
    momento_emissao timestamp with time zone NOT NULL,
    observacoes character varying(250),
    anulado boolean DEFAULT false NOT NULL,
    impresso boolean DEFAULT false NOT NULL,
    codigo_validacao_at character varying(100),
    atcud character varying(150),
    qr_payload text,
    qr_payload_version character varying(20),
    CONSTRAINT ck_documento_financeiro_valores CHECK (((valor_pagamento_bruto >= (0)::numeric) AND (valor_desconto_financeiro >= (0)::numeric) AND (valor_desconto_financeiro <= valor_pagamento_bruto) AND (valor_pagamento_liquido = (valor_pagamento_bruto - valor_desconto_financeiro))))
);


--
-- Name: documento_financeiro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documento_financeiro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documento_financeiro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empresa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empresa (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    nif character varying(20) NOT NULL,
    morada character varying(60) NOT NULL,
    morada1 character varying(60),
    id_codpostal character varying(20) NOT NULL,
    localidade character varying(50) NOT NULL,
    id_pais character varying(3) NOT NULL,
    id_freguesia character varying(6),
    capital_social numeric(19,2) NOT NULL,
    matricula_registo_comercial character varying(100) NOT NULL,
    cae character varying(10) NOT NULL,
    descricao_cae character varying(100) NOT NULL,
    email character varying(120) NOT NULL,
    web character varying(120),
    CONSTRAINT ck_empresa_capital_social CHECK ((capital_social >= (0)::numeric)),
    CONSTRAINT ck_empresa_unica CHECK ((id = 1))
);


--
-- Name: familia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.familia (
    id bigint NOT NULL,
    descricao character varying(30) NOT NULL
);


--
-- Name: familia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.familia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.familia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: freguesia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.freguesia (
    codigo character varying(6) NOT NULL,
    codigo_distrito character varying(2) NOT NULL,
    codigo_concelho character varying(2) NOT NULL,
    codigo_freguesia character varying(2) NOT NULL,
    concelho character varying(50) NOT NULL,
    nome character varying(80) NOT NULL,
    extinta boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_freguesia_codigo CHECK (((codigo)::text = (((codigo_distrito)::text || (codigo_concelho)::text) || (codigo_freguesia)::text)))
);


--
-- Name: ivasaft; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ivasaft (
    id character varying(3) NOT NULL,
    nome character varying(50) NOT NULL
);


--
-- Name: linha_documento_comercial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.linha_documento_comercial (
    id bigint NOT NULL,
    id_documento_comercial bigint NOT NULL,
    numero_linha integer NOT NULL,
    id_artigo character varying(50) NOT NULL,
    descricao character varying(80) NOT NULL,
    quantidade numeric(19,6) NOT NULL,
    preco_unitario numeric(19,6) NOT NULL,
    valor_bruto numeric(19,6) NOT NULL,
    tipo_desconto character varying(20) NOT NULL,
    desconto numeric(19,6) NOT NULL,
    valor_desconto numeric(19,6) NOT NULL,
    valor_linha numeric(19,6) NOT NULL,
    id_tipo_taxa_iva character varying(20) NOT NULL,
    percentagem_iva numeric(5,2) NOT NULL,
    peso numeric(15,3),
    CONSTRAINT ck_linha_documento_comercial_desconto CHECK (((desconto >= (0)::numeric) AND (valor_desconto >= (0)::numeric) AND (valor_desconto <= valor_bruto))),
    CONSTRAINT ck_linha_documento_comercial_peso CHECK (((peso IS NULL) OR (peso >= (0)::numeric))),
    CONSTRAINT ck_linha_documento_comercial_preco CHECK ((preco_unitario >= (0)::numeric)),
    CONSTRAINT ck_linha_documento_comercial_quantidade CHECK ((quantidade > (0)::numeric)),
    CONSTRAINT ck_linha_documento_comercial_tipo_desconto CHECK (((tipo_desconto)::text = ANY ((ARRAY['PERCENTAGEM'::character varying, 'VALOR'::character varying])::text[]))),
    CONSTRAINT ck_linha_documento_comercial_valor CHECK ((valor_linha = (valor_bruto - valor_desconto)))
);


--
-- Name: linha_documento_comercial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.linha_documento_comercial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.linha_documento_comercial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: linha_documento_financeiro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.linha_documento_financeiro (
    id bigint NOT NULL,
    id_documento_financeiro bigint NOT NULL,
    numero_linha integer NOT NULL,
    id_pendente bigint NOT NULL,
    valor_pendente_antes numeric(19,6) NOT NULL,
    valor_pagamento_bruto numeric(19,6) NOT NULL,
    valor_desconto_financeiro numeric(19,6) DEFAULT 0 NOT NULL,
    valor_pagamento_liquido numeric(19,6) NOT NULL,
    data_documento date DEFAULT CURRENT_DATE NOT NULL,
    data_vencimento date DEFAULT CURRENT_DATE NOT NULL,
    id_tipo_documento character varying(3),
    numero_documento bigint DEFAULT 0 NOT NULL,
    serie_documento character varying(10) DEFAULT ''::character varying NOT NULL,
    valor_documento numeric(19,6) DEFAULT 0 NOT NULL,
    desconto_percentual numeric(9,6),
    novo_valor_pendente numeric(19,6) DEFAULT 0 NOT NULL,
    id_moeda character varying(3),
    CONSTRAINT ck_linha_documento_financeiro_valores CHECK (((valor_pendente_antes > (0)::numeric) AND (valor_pagamento_bruto > (0)::numeric) AND (valor_pagamento_bruto <= valor_pendente_antes) AND (valor_desconto_financeiro >= (0)::numeric) AND (valor_desconto_financeiro <= valor_pagamento_bruto) AND (valor_pagamento_liquido = (valor_pagamento_bruto - valor_desconto_financeiro))))
);


--
-- Name: linha_documento_financeiro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.linha_documento_financeiro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.linha_documento_financeiro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: misencao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.misencao (
    id character varying(3) NOT NULL,
    nome character varying(60) NOT NULL,
    id_ivasaft character varying(4) NOT NULL
);


--
-- Name: moeda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.moeda (
    id character varying(3) NOT NULL,
    nome character varying(30) NOT NULL,
    vcompra numeric(20,10),
    vvenda numeric(20,10),
    simbolo character varying(5) NOT NULL,
    ndecimais integer NOT NULL,
    ciso character varying(10)
);


--
-- Name: morada; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.morada (
    id bigint NOT NULL,
    id_cliente bigint NOT NULL,
    nome character varying(80) NOT NULL,
    morada character varying(60) NOT NULL,
    morada1 character varying(60),
    localidade character varying(50),
    id_codpostal character varying(20) NOT NULL,
    tipo character varying(20) NOT NULL,
    principal boolean DEFAULT false NOT NULL,
    inativo boolean DEFAULT false NOT NULL
);


--
-- Name: morada_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.morada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.morada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mpagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mpagamento (
    id integer NOT NULL,
    nome character varying(30) NOT NULL
);


--
-- Name: mpagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mpagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mpagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pais (
    id character varying(3) NOT NULL,
    nome character varying(50) NOT NULL
);


--
-- Name: parametros_aplicacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parametros_aplicacao (
    id bigint NOT NULL,
    atraso_carga_minutos integer NOT NULL,
    decimais_quantidade integer NOT NULL,
    decimais_valor integer NOT NULL,
    CONSTRAINT ck_parametros_aplicacao_atraso CHECK (((atraso_carga_minutos >= 0) AND (atraso_carga_minutos <= 120))),
    CONSTRAINT ck_parametros_aplicacao_decimais_quantidade CHECK (((decimais_quantidade >= 0) AND (decimais_quantidade <= 6))),
    CONSTRAINT ck_parametros_aplicacao_decimais_valor CHECK (((decimais_valor >= 0) AND (decimais_valor <= 6))),
    CONSTRAINT ck_parametros_aplicacao_unico CHECK ((id = 1))
);


--
-- Name: parametros_cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parametros_cliente (
    id bigint NOT NULL,
    id_pais character varying(3),
    id_moeda character varying(3),
    id_riva character varying(3),
    id_mpagamento integer,
    id_ppagamento character varying(3),
    id_transporte integer,
    retencao boolean,
    CONSTRAINT ck_parametros_cliente_unico CHECK ((id = 1))
);


--
-- Name: parametros_documento_comercial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parametros_documento_comercial (
    id bigint NOT NULL,
    id_tipo_documento character varying(3),
    serie character varying(10),
    id_armazem_carga bigint,
    CONSTRAINT ck_parametros_documento_serie_completa CHECK ((((id_tipo_documento IS NULL) AND (serie IS NULL)) OR ((id_tipo_documento IS NOT NULL) AND (serie IS NOT NULL)))),
    CONSTRAINT ck_parametros_documento_unico CHECK ((id = 1))
);


--
-- Name: pendente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pendente (
    id bigint NOT NULL,
    id_documento_comercial bigint NOT NULL,
    id_cliente bigint NOT NULL,
    id_tipo_documento character varying(3) NOT NULL,
    numero_documento bigint NOT NULL,
    serie_documento character varying(10) NOT NULL,
    valor_documento numeric(19,6) NOT NULL,
    valor_pendente numeric(19,6) NOT NULL,
    data_documento date NOT NULL,
    data_vencimento date NOT NULL,
    id_moeda character varying(3) NOT NULL,
    CONSTRAINT ck_pendente_valores CHECK (((valor_documento > (0)::numeric) AND (valor_pendente >= (0)::numeric) AND (valor_pendente <= valor_documento)))
);


--
-- Name: pendente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pendente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pendente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ppagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ppagamento (
    id character varying(3) NOT NULL,
    nome character varying(30) NOT NULL,
    dias integer NOT NULL
);


--
-- Name: riva; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.riva (
    id character varying(3) NOT NULL,
    nome character varying(30) NOT NULL
);


--
-- Name: riva_taxa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.riva_taxa (
    id bigint NOT NULL,
    id_riva character varying(3) NOT NULL,
    id_tipo_taxa_iva character varying(20) NOT NULL,
    valor numeric(4,2) NOT NULL
);


--
-- Name: riva_taxa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.riva_taxa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.riva_taxa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: serie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.serie (
    serie character varying(10) NOT NULL,
    id_tipo_documento character varying(3) NOT NULL,
    nome character varying(50) NOT NULL,
    codigo_at character varying(100),
    data_codigo_at date,
    numerador bigint DEFAULT 0 NOT NULL
);

CREATE TABLE public.tipodocumento (
    id character varying(3) NOT NULL,
    descricao character varying(50) NOT NULL,
    modelo_emissao1 character varying(25),
    modelo_emissao2 character varying(25),
    modelo_emissao3 character varying(25),
    modelo_emissao4 character varying(25),
    area_gestao integer NOT NULL,
    entidade integer NOT NULL,
    sinal_contabilistico integer NOT NULL,
    liquidacao_imediata boolean DEFAULT false NOT NULL,
    codigo_fiscal character varying(2)
);

CREATE TABLE public.tipotaxaiva (
    id character varying(20) NOT NULL,
    descricao character varying(50) NOT NULL,
    inativo boolean DEFAULT false NOT NULL
);

CREATE TABLE public.transporte (
    id integer NOT NULL,
    nome character varying(30) NOT NULL
);

ALTER TABLE public.transporte ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transporte_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.utilizador (
    codigo character varying(20) NOT NULL,
    nome character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password_hash character varying(60) NOT NULL,
    inativo boolean DEFAULT false NOT NULL
);

ALTER TABLE ONLY public.armazem ADD CONSTRAINT armazem_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.artigo ADD CONSTRAINT artigo_codigo_identificacao_key UNIQUE (codigo_identificacao);
ALTER TABLE ONLY public.artigo ADD CONSTRAINT artigo_pkey PRIMARY KEY (codigo);
ALTER TABLE ONLY public.cliente ADD CONSTRAINT cliente_nif_key UNIQUE (nif);
ALTER TABLE ONLY public.cliente ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.codpostal ADD CONSTRAINT codpostal_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.documento_comercial ADD CONSTRAINT documento_comercial_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.documento_financeiro ADD CONSTRAINT documento_financeiro_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.empresa ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.familia ADD CONSTRAINT familia_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.freguesia ADD CONSTRAINT freguesia_pkey PRIMARY KEY (codigo);
ALTER TABLE ONLY public.ivasaft ADD CONSTRAINT ivasaft_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.linha_documento_comercial ADD CONSTRAINT linha_documento_comercial_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.linha_documento_financeiro ADD CONSTRAINT linha_documento_financeiro_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.misencao ADD CONSTRAINT misencao_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.moeda ADD CONSTRAINT moeda_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.morada ADD CONSTRAINT morada_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.mpagamento ADD CONSTRAINT mpagamento_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pais ADD CONSTRAINT pais_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parametros_aplicacao ADD CONSTRAINT parametros_aplicacao_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parametros_cliente ADD CONSTRAINT parametros_cliente_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parametros_documento_comercial ADD CONSTRAINT parametros_documento_comercial_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pendente ADD CONSTRAINT pendente_id_documento_comercial_key UNIQUE (id_documento_comercial);


--
-- Name: pendente pendente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pendente
    ADD CONSTRAINT pendente_pkey PRIMARY KEY (id);


--
-- Name: serie pk_serie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.serie
    ADD CONSTRAINT pk_serie PRIMARY KEY (id_tipo_documento, serie);


--
-- Name: ppagamento ppagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ppagamento
    ADD CONSTRAINT ppagamento_pkey PRIMARY KEY (id);


--
-- Name: riva riva_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.riva
    ADD CONSTRAINT riva_pkey PRIMARY KEY (id);


--
-- Name: riva_taxa riva_taxa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.riva_taxa
    ADD CONSTRAINT riva_taxa_pkey PRIMARY KEY (id);


--
-- Name: tipodocumento tipodocumento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipodocumento
    ADD CONSTRAINT tipodocumento_pkey PRIMARY KEY (id);


--
-- Name: tipotaxaiva tipotaxaiva_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipotaxaiva
    ADD CONSTRAINT tipotaxaiva_pkey PRIMARY KEY (id);


--
-- Name: transporte transporte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transporte
    ADD CONSTRAINT transporte_pkey PRIMARY KEY (id);


--
-- Name: documento_comercial uk_documento_comercial_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT uk_documento_comercial_numero UNIQUE (id_tipo_documento, serie, numero_documento);


--
-- Name: documento_financeiro uk_documento_financeiro_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT uk_documento_financeiro_numero UNIQUE (id_tipo_documento, serie, numero_documento);


--
-- Name: linha_documento_comercial uk_linha_documento_comercial_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_comercial
    ADD CONSTRAINT uk_linha_documento_comercial_numero UNIQUE (id_documento_comercial, numero_linha);


--
-- Name: linha_documento_financeiro uk_linha_documento_financeiro_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_financeiro
    ADD CONSTRAINT uk_linha_documento_financeiro_numero UNIQUE (id_documento_financeiro, numero_linha);


--
-- Name: riva_taxa uk_riva_taxa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.riva_taxa
    ADD CONSTRAINT uk_riva_taxa UNIQUE (id_riva, id_tipo_taxa_iva);


--
-- Name: utilizador utilizador_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilizador
    ADD CONSTRAINT utilizador_email_key UNIQUE (email);


--
-- Name: utilizador utilizador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilizador
    ADD CONSTRAINT utilizador_pkey PRIMARY KEY (codigo);


--
-- Name: ix_cliente_pais; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cliente_pais ON public.cliente USING btree (id_pais);


--
-- Name: ix_linha_documento_comercial_documento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_linha_documento_comercial_documento ON public.linha_documento_comercial USING btree (id_documento_comercial);


--
-- Name: ix_linha_documento_financeiro_documento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_linha_documento_financeiro_documento ON public.linha_documento_financeiro USING btree (id_documento_financeiro);


--
-- Name: ix_linha_documento_financeiro_pendente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_linha_documento_financeiro_pendente ON public.linha_documento_financeiro USING btree (id_pendente);


--
-- Name: ix_pendente_cliente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pendente_cliente ON public.pendente USING btree (id_cliente);


--
-- Name: ix_pendente_documento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pendente_documento ON public.pendente USING btree (id_tipo_documento, serie_documento, numero_documento);


--
-- Name: ix_pendente_vencimento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pendente_vencimento ON public.pendente USING btree (data_vencimento);


--
-- Name: armazem armazem_id_codpostal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armazem
    ADD CONSTRAINT armazem_id_codpostal_fkey FOREIGN KEY (id_codpostal) REFERENCES public.codpostal(id);


--
-- Name: armazem armazem_id_freguesia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armazem
    ADD CONSTRAINT armazem_id_freguesia_fkey FOREIGN KEY (id_freguesia) REFERENCES public.freguesia(codigo);


--
-- Name: armazem armazem_id_pais_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armazem
    ADD CONSTRAINT armazem_id_pais_fkey FOREIGN KEY (id_pais) REFERENCES public.pais(id);


--
-- Name: artigo artigo_id_familia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artigo
    ADD CONSTRAINT artigo_id_familia_fkey FOREIGN KEY (id_familia) REFERENCES public.familia(id);


--
-- Name: artigo artigo_id_iva_compra_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artigo
    ADD CONSTRAINT artigo_id_iva_compra_fkey FOREIGN KEY (id_iva_compra) REFERENCES public.tipotaxaiva(id);


--
-- Name: artigo artigo_id_iva_venda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artigo
    ADD CONSTRAINT artigo_id_iva_venda_fkey FOREIGN KEY (id_iva_venda) REFERENCES public.tipotaxaiva(id);


--
-- Name: cliente cliente_id_codpostal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_codpostal_fkey FOREIGN KEY (id_codpostal) REFERENCES public.codpostal(id);


--
-- Name: cliente cliente_id_moeda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_moeda_fkey FOREIGN KEY (id_moeda) REFERENCES public.moeda(id);


--
-- Name: cliente cliente_id_mpagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_mpagamento_fkey FOREIGN KEY (id_mpagamento) REFERENCES public.mpagamento(id);


--
-- Name: cliente cliente_id_pais_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_pais_fkey FOREIGN KEY (id_pais) REFERENCES public.pais(id);


--
-- Name: cliente cliente_id_ppagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_ppagamento_fkey FOREIGN KEY (id_ppagamento) REFERENCES public.ppagamento(id);


--
-- Name: cliente cliente_id_riva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_riva_fkey FOREIGN KEY (id_riva) REFERENCES public.riva(id);


--
-- Name: cliente cliente_id_transporte_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_id_transporte_fkey FOREIGN KEY (id_transporte) REFERENCES public.transporte(id);


--
-- Name: documento_comercial documento_comercial_id_armazem_carga_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_armazem_carga_fkey FOREIGN KEY (id_armazem_carga) REFERENCES public.armazem(id);


--
-- Name: documento_comercial documento_comercial_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


--
-- Name: documento_comercial documento_comercial_id_emissor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_emissor_fkey FOREIGN KEY (id_emissor) REFERENCES public.utilizador(codigo);


--
-- Name: documento_comercial documento_comercial_id_moeda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_moeda_fkey FOREIGN KEY (id_moeda) REFERENCES public.moeda(id);


--
-- Name: documento_comercial documento_comercial_id_morada_envio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_morada_envio_fkey FOREIGN KEY (id_morada_envio) REFERENCES public.morada(id);


--
-- Name: documento_comercial documento_comercial_id_mpagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_mpagamento_fkey FOREIGN KEY (id_mpagamento) REFERENCES public.mpagamento(id);


--
-- Name: documento_comercial documento_comercial_id_ppagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_ppagamento_fkey FOREIGN KEY (id_ppagamento) REFERENCES public.ppagamento(id);


--
-- Name: documento_comercial documento_comercial_id_riva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_riva_fkey FOREIGN KEY (id_riva) REFERENCES public.riva(id);


--
-- Name: documento_comercial documento_comercial_id_tipo_documento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_tipo_documento_fkey FOREIGN KEY (id_tipo_documento) REFERENCES public.tipodocumento(id);


--
-- Name: documento_comercial documento_comercial_id_transporte_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT documento_comercial_id_transporte_fkey FOREIGN KEY (id_transporte) REFERENCES public.transporte(id);


--
-- Name: documento_financeiro documento_financeiro_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT documento_financeiro_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


--
-- Name: documento_financeiro documento_financeiro_id_emissor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT documento_financeiro_id_emissor_fkey FOREIGN KEY (id_emissor) REFERENCES public.utilizador(codigo);


--
-- Name: documento_financeiro documento_financeiro_id_moeda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT documento_financeiro_id_moeda_fkey FOREIGN KEY (id_moeda) REFERENCES public.moeda(id);


--
-- Name: documento_financeiro documento_financeiro_id_mpagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT documento_financeiro_id_mpagamento_fkey FOREIGN KEY (id_mpagamento) REFERENCES public.mpagamento(id);


--
-- Name: documento_financeiro documento_financeiro_id_tipo_documento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT documento_financeiro_id_tipo_documento_fkey FOREIGN KEY (id_tipo_documento) REFERENCES public.tipodocumento(id);


--
-- Name: empresa empresa_id_codpostal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_id_codpostal_fkey FOREIGN KEY (id_codpostal) REFERENCES public.codpostal(id);


--
-- Name: empresa empresa_id_freguesia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_id_freguesia_fkey FOREIGN KEY (id_freguesia) REFERENCES public.freguesia(codigo);


--
-- Name: empresa empresa_id_pais_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_id_pais_fkey FOREIGN KEY (id_pais) REFERENCES public.pais(id);


--
-- Name: documento_comercial fk_documento_comercial_serie; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_comercial
    ADD CONSTRAINT fk_documento_comercial_serie FOREIGN KEY (id_tipo_documento, serie) REFERENCES public.serie(id_tipo_documento, serie);


--
-- Name: documento_financeiro fk_documento_financeiro_serie; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_financeiro
    ADD CONSTRAINT fk_documento_financeiro_serie FOREIGN KEY (id_tipo_documento, serie) REFERENCES public.serie(id_tipo_documento, serie);


--
-- Name: parametros_documento_comercial fk_parametros_documento_serie; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_documento_comercial
    ADD CONSTRAINT fk_parametros_documento_serie FOREIGN KEY (id_tipo_documento, serie) REFERENCES public.serie(id_tipo_documento, serie);


--
-- Name: linha_documento_comercial linha_documento_comercial_id_artigo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_comercial
    ADD CONSTRAINT linha_documento_comercial_id_artigo_fkey FOREIGN KEY (id_artigo) REFERENCES public.artigo(codigo);


--
-- Name: linha_documento_comercial linha_documento_comercial_id_documento_comercial_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_comercial
    ADD CONSTRAINT linha_documento_comercial_id_documento_comercial_fkey FOREIGN KEY (id_documento_comercial) REFERENCES public.documento_comercial(id);


--
-- Name: linha_documento_comercial linha_documento_comercial_id_tipo_taxa_iva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_comercial
    ADD CONSTRAINT linha_documento_comercial_id_tipo_taxa_iva_fkey FOREIGN KEY (id_tipo_taxa_iva) REFERENCES public.tipotaxaiva(id);


--
-- Name: linha_documento_financeiro linha_documento_financeiro_id_documento_financeiro_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_financeiro
    ADD CONSTRAINT linha_documento_financeiro_id_documento_financeiro_fkey FOREIGN KEY (id_documento_financeiro) REFERENCES public.documento_financeiro(id);


--
-- Name: linha_documento_financeiro linha_documento_financeiro_id_moeda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_financeiro
    ADD CONSTRAINT linha_documento_financeiro_id_moeda_fkey FOREIGN KEY (id_moeda) REFERENCES public.moeda(id);


--
-- Name: linha_documento_financeiro linha_documento_financeiro_id_pendente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_financeiro
    ADD CONSTRAINT linha_documento_financeiro_id_pendente_fkey FOREIGN KEY (id_pendente) REFERENCES public.pendente(id);


--
-- Name: linha_documento_financeiro linha_documento_financeiro_id_tipo_documento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linha_documento_financeiro
    ADD CONSTRAINT linha_documento_financeiro_id_tipo_documento_fkey FOREIGN KEY (id_tipo_documento) REFERENCES public.tipodocumento(id);


--
-- Name: misencao misencao_id_ivasaft_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.misencao
    ADD CONSTRAINT misencao_id_ivasaft_fkey FOREIGN KEY (id_ivasaft) REFERENCES public.ivasaft(id);


--
-- Name: morada morada_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.morada
    ADD CONSTRAINT morada_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


--
-- Name: morada morada_id_codpostal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.morada
    ADD CONSTRAINT morada_id_codpostal_fkey FOREIGN KEY (id_codpostal) REFERENCES public.codpostal(id);


--
-- Name: parametros_cliente parametros_cliente_id_moeda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_cliente
    ADD CONSTRAINT parametros_cliente_id_moeda_fkey FOREIGN KEY (id_moeda) REFERENCES public.moeda(id);


--
-- Name: parametros_cliente parametros_cliente_id_mpagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_cliente
    ADD CONSTRAINT parametros_cliente_id_mpagamento_fkey FOREIGN KEY (id_mpagamento) REFERENCES public.mpagamento(id);


--
-- Name: parametros_cliente parametros_cliente_id_pais_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_cliente
    ADD CONSTRAINT parametros_cliente_id_pais_fkey FOREIGN KEY (id_pais) REFERENCES public.pais(id);


--
-- Name: parametros_cliente parametros_cliente_id_ppagamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_cliente
    ADD CONSTRAINT parametros_cliente_id_ppagamento_fkey FOREIGN KEY (id_ppagamento) REFERENCES public.ppagamento(id);


--
-- Name: parametros_cliente parametros_cliente_id_riva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_cliente
    ADD CONSTRAINT parametros_cliente_id_riva_fkey FOREIGN KEY (id_riva) REFERENCES public.riva(id);


--
-- Name: parametros_cliente parametros_cliente_id_transporte_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_cliente
    ADD CONSTRAINT parametros_cliente_id_transporte_fkey FOREIGN KEY (id_transporte) REFERENCES public.transporte(id);


--
-- Name: parametros_documento_comercial parametros_documento_comercial_id_armazem_carga_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametros_documento_comercial
    ADD CONSTRAINT parametros_documento_comercial_id_armazem_carga_fkey FOREIGN KEY (id_armazem_carga) REFERENCES public.armazem(id);


--
-- Name: pendente pendente_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pendente
    ADD CONSTRAINT pendente_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


--
-- Name: pendente pendente_id_documento_comercial_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pendente
    ADD CONSTRAINT pendente_id_documento_comercial_fkey FOREIGN KEY (id_documento_comercial) REFERENCES public.documento_comercial(id);


--
-- Name: pendente pendente_id_moeda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pendente
    ADD CONSTRAINT pendente_id_moeda_fkey FOREIGN KEY (id_moeda) REFERENCES public.moeda(id);


--
-- Name: pendente pendente_id_tipo_documento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pendente
    ADD CONSTRAINT pendente_id_tipo_documento_fkey FOREIGN KEY (id_tipo_documento) REFERENCES public.tipodocumento(id);


--
-- Name: riva_taxa riva_taxa_id_riva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.riva_taxa
    ADD CONSTRAINT riva_taxa_id_riva_fkey FOREIGN KEY (id_riva) REFERENCES public.riva(id);


--
-- Name: riva_taxa riva_taxa_id_tipo_taxa_iva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.riva_taxa
    ADD CONSTRAINT riva_taxa_id_tipo_taxa_iva_fkey FOREIGN KEY (id_tipo_taxa_iva) REFERENCES public.tipotaxaiva(id);


--
-- Name: serie serie_id_tipo_documento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.serie
    ADD CONSTRAINT serie_id_tipo_documento_fkey FOREIGN KEY (id_tipo_documento) REFERENCES public.tipodocumento(id);


--
-- PostgreSQL database dump complete
--



-- Dados de referência mínimos; não são dados comerciais nem documentos fiscais.
INSERT INTO public.pais (id, nome) VALUES ('PT', 'Portugal');
INSERT INTO public.freguesia (codigo, codigo_distrito, codigo_concelho, codigo_freguesia, concelho, nome, extinta)
VALUES ('010103', '01', '01', '03', 'Águeda', 'Águeda e Borralha', false);
INSERT INTO public.moeda (id, nome, vcompra, vvenda, simbolo, ndecimais, ciso)
VALUES ('EUR', 'Euro', 1, 1, 'EUR', 2, '978');
INSERT INTO public.tipotaxaiva (id, descricao, inativo) VALUES
 ('ISENTA', 'Isenta', false), ('REDUZIDA', 'Reduzida', false),
 ('INTERMEDIA', 'Intermédia', false), ('NORMAL', 'Normal', false);
INSERT INTO public.riva (id, nome) VALUES ('CON', 'Continente');
INSERT INTO public.riva_taxa (id_riva, id_tipo_taxa_iva, valor) VALUES
 ('CON', 'ISENTA', 0), ('CON', 'REDUZIDA', 6), ('CON', 'INTERMEDIA', 13), ('CON', 'NORMAL', 23);
INSERT INTO public.ppagamento (id, nome, dias) VALUES ('P30', '30 dias', 30);
