-- Bloco 3: anulacao documental, papeis funcionais e auditoria append-only.
-- Compatibilidade controlada: utilizadores existentes recebem ADMIN. Rever antes de producao.

ALTER TABLE public.utilizador
    ADD COLUMN papel character varying(20) NOT NULL DEFAULT 'ADMIN';

ALTER TABLE public.utilizador
    ADD CONSTRAINT ck_utilizador_papel CHECK (papel IN ('ADMIN', 'OPERADOR', 'CONSULTA'));

ALTER TABLE public.documento_comercial
    ADD COLUMN motivo_anulacao character varying(500),
    ADD COLUMN data_hora_anulacao timestamp with time zone,
    ADD COLUMN anulado_por_utilizador_id character varying(20),
    ADD COLUMN anulado_por_nome character varying(100);

ALTER TABLE public.documento_comercial
    DROP CONSTRAINT ck_documento_comercial_estado;

-- Estado passa a fonte oficial, sem tocar em numero, ATCUD, QR ou snapshots fiscais.
UPDATE public.documento_comercial
SET estado = 'ANULADO'
WHERE anulado = true;

UPDATE public.documento_comercial
SET anulado = (estado = 'ANULADO');

ALTER TABLE public.documento_comercial
    ADD CONSTRAINT ck_documento_comercial_estado
        CHECK (estado IN ('RASCUNHO', 'EMITIDO', 'ANULADO')),
    ADD CONSTRAINT ck_documento_comercial_estado_anulado
        CHECK ((estado = 'ANULADO') = anulado),
    ADD CONSTRAINT ck_documento_comercial_dados_anulacao
        CHECK (
            (estado <> 'ANULADO') OR
            (motivo_anulacao IS NULL AND data_hora_anulacao IS NULL
             AND anulado_por_utilizador_id IS NULL AND anulado_por_nome IS NULL) OR
            (motivo_anulacao IS NOT NULL AND length(btrim(motivo_anulacao)) BETWEEN 5 AND 500
             AND data_hora_anulacao IS NOT NULL
             AND anulado_por_utilizador_id IS NOT NULL
             AND anulado_por_nome IS NOT NULL)
        );

CREATE TABLE public.auditoria_evento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamp with time zone NOT NULL,
    tipo_evento character varying(50) NOT NULL,
    entidade_tipo character varying(50) NOT NULL,
    entidade_id character varying(100) NOT NULL,
    utilizador_id character varying(20),
    utilizador_nome character varying(100),
    resultado character varying(20) NOT NULL,
    descricao character varying(500) NOT NULL,
    dados_essenciais text NOT NULL DEFAULT '{}',
    CONSTRAINT ck_auditoria_resultado CHECK (resultado IN ('SUCESSO', 'FALHA'))
);

CREATE INDEX ix_auditoria_data_hora ON public.auditoria_evento (data_hora DESC);
CREATE INDEX ix_auditoria_tipo_data ON public.auditoria_evento (tipo_evento, data_hora DESC);
CREATE INDEX ix_auditoria_entidade ON public.auditoria_evento (entidade_tipo, entidade_id, data_hora DESC);
CREATE INDEX ix_auditoria_utilizador ON public.auditoria_evento (utilizador_id, data_hora DESC);
CREATE INDEX ix_documento_comercial_estado ON public.documento_comercial (estado);
